[View in Colaboratory](https://colab.research.google.com/github/banka01/ai_ml/blob/master/Assignment1_Matrix_mulitiplication.ipynb)

Matrix Multiplication. using normal list.


In [5]:
import sys
r1=int(input('enter rows for M1:'))
c1=int(input('enter cols for M1:'))
r2=int(input('enter rows for M2:'))
c2=int(input('enter cols for M2:'))
if (c1==r2 ) is False:
    print("Matrix Multiplication is not possible")
    sys.exit(0)
    

mat1 = [[0 for j in range(c1)] for i in range(r1)]
mat2 = [[0 for j in range(c2)] for i in range(r2)]
result_matrix = [[0 for j in range(c2)] for i in range(r1)]
print('Enter elements for matrix1')
for i in range(r1):
    for j in range(c1):
        mat1[i][j]=int(input())

print('Enter elements for matrix2')
for i in range(r2):
    for j in range(c2):
        mat2[i][j]=int(input())
        
## logic for matrix multiplication.
## for each row of mat1:
for i in range(r1):
    # for each column of mat2:
    for j in range(c2):
        # for each row of mat 2:
        for k in range(r2):
            result_matrix[i][j] += mat1[i][k] * mat2[k][j]
print("Elements of Matrix1")
for r in mat1:
    print(r)
print('-'*10)
print("Elements of Matrix1")
for r in mat2:
    print(r)
print('-'*10)
print("Elements of Results Matrix")
for r in result_matrix:
    print(r)

enter rows for M1:2
enter cols for M1:3
enter rows for M2:3
enter cols for M2:2
Enter elements for matrix1
1
2
3
4
5
6
Enter elements for matrix2
1
2
3
4
5
6
Elements of Matrix1
[1, 2, 3]
[4, 5, 6]
----------
Elements of Matrix1
[1, 2]
[3, 4]
[5, 6]
----------
Elements of Results Matrix
[22, 28]
[49, 64]


**Matrix multiplication using numpy**

In [8]:
import numpy as np
import sys

# get the rows and cols for MatrixA
r1=int(input('enter rows for M1:')) 
c1=int(input('enter cols for M1:'))
# get the rows and cols for MatrixB
r2=int(input('enter rows for M2:'))
c2=int(input('enter cols for M2:'))

# check if Matrix multiply is possible
if (c1==r2 ) is False:
    print("Matrix Multiplication is not possible")
    sys.exit(0)
    
## generate random matrix A for r1,c1 dimension
m1 = np.random.randint(0,1000,(r1,c1))
## generate random matrix B for r2,c2 dimension
m2 = np.random.randint(0,1000,(r2,c2))


## result matrix containing all zeros
result_matrix= np.zeros((r1,c2))
## matrix mulitplilcation
result_matrix = m1.dot(m2)
## print for all matrix
print(m1)
print(m2)
print(result_matrix)

enter rows for M1:2
enter cols for M1:2
enter rows for M2:2
enter cols for M2:2
[[36 28]
 [41 56]]
[[36 32]
 [ 1 26]]
[[1324 1880]
 [1532 2768]]


**Function for the fibonacci nos using recursion**

In [9]:
def fib_ns(n):
  if n<=1:
    return n
  else:
    return(fib_ns(n-1)+fib_ns(n-2))
nos= int(input('enter count of fibonacci nos required'))
for i in range(nos):
  print(fib_ns(i))

enter count of fibonacci nos required10
0
1
1
2
3
5
8
13
21
34


**Reverse a List**

In [11]:
values=[1,2,3,'ai','ml']
values.reverse()
print(values)
print(values[::-1])

['ml', 'ai', 3, 2, 1]
[1, 2, 3, 'ai', 'ml']
