#step0 input and output init

In [1]:
import numpy as np
x = [1,0,1,0,1,0,1,1,0,1,0,1]
x = np.array(x)
#reshapes the input array in 3 rows and four columns
X=x.reshape(3,4)
print("Input X")
print(X)

y=[1,1,0]
y=np.array(y)
Y=y.reshape(3,1)
print("Output Y")
print(Y)

Input X
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Output Y
[[1]
 [1]
 [0]]


Step 1: . Weights generation

In [2]:
## get the random weights as 4*3 matrix
wh = np.around(np.random.rand(4,3),decimals=2)
print("WH matrix 4*3")
print(wh)
bh = np.around(np.random.rand(1,3),decimals=2)
print("BH matrix")
print(bh)
wout = np.around(np.random.rand(3,1),decimals=2)
print("wout matrix")
print(wout)
bout = np.around(np.random.rand(1,1),decimals=2)
print("bout matrix")
print(bout)

## hidden layer input matrix init
hidden_layer_input = np.around(np.zeros((3,3)),decimals=2)
## hidden layer activation matrox init
hidden_layer_activations = np.around(np.zeros((3,3)),decimals=2)

## output matrix init
output = np.around(np.zeros((3,1)),decimals=2)
## Error E matrix init
E = np.around(np.zeros((3,1)),decimals=2)


WH matrix 4*3
[[0.15 0.37 0.25]
 [0.28 0.76 0.77]
 [0.99 0.26 0.66]
 [0.34 0.45 0.2 ]]
BH matrix
[[0.43 0.73 0.83]]
wout matrix
[[0.07]
 [0.76]
 [0.78]]
bout matrix
[[0.77]]


Step 2: Calculate hidden layer input

In [3]:
hidden_layer_input = X.dot(wh) + bh
print(hidden_layer_input)

[[1.57 1.36 1.74]
 [1.91 1.81 1.94]
 [1.05 1.94 1.8 ]]


step 3: calculate hidden layer activations


In [4]:
def sigmoid(hypoth):
    sig = 1/(1+np.exp(-1.0 * hypoth))
    return np.around(sig,decimals=2)

hidden_layer_activations=sigmoid(hidden_layer_input)
print(hidden_layer_activations)

[[0.83 0.8  0.85]
 [0.87 0.86 0.87]
 [0.74 0.87 0.86]]


step 4 : Perform linear and non-linear transformation of hidden layer activation at output layer

In [5]:
output_layer_hidden = hidden_layer_activations.dot(wout) + bout

output = sigmoid(output_layer_hidden)
print(output)

[[0.89]
 [0.9 ]
 [0.9 ]]


In [6]:
E = Y-output
print(E)

[[ 0.11]
 [ 0.1 ]
 [-0.9 ]]
